# Generated by Django 6.0.1 on 2026-01-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_tags', '0001_initial'),
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories_tags.category'),
        ),
    ]
